version: "3"

services:
  backend:
    build: rust_server
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db/postgres
  db:
    image: postgres
    restart: always
    container_name: backend_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    restart: always
    container_name: backend_adminer
    depends_on:
      - db
    ports:
      - 8080:8080
