[package]
name = "rust_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
reqwest = {version = "0.11.23", features = ["json", "cookies", "multipart"]}
rocket = {version = "0.5.0", features = ["secrets", "json"]}
rocket_dyn_templates = {version = "0.1.0", features = ["tera"]}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
