[package]
name = "rust_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
rocket_dyn_templates = {version = "0.1.0", features = ["tera"]}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
